name: 'facetsctl-action-push'
description: 'Download and run facetsctl commands'
inputs:
  control-plane-url:
    description: 'URL of the Facets Control plane'
    required: true
  token:
    description: 'Personal token'
    required: true
  username:
    description: 'Username'
    required: true
  project:
    description: 'Project name'
    required: true
  service:
    description: 'Service name'
    required: true
  artifactory:
    description: 'Artifactory name'
    required: true
  docker-image:
    description: 'Docker image to push'
    required: false
  register-type:
    description: 'Type for register command (GIT_REF|ENVIRONMENT|RELEASE_STREAM)'
    required: true
  register-value:
    description: 'Value for the specified register type'
    required: true
  push:
    description: 'Whether to push the Docker image'
    required: false
    default: 'true'

runs:
  using: 'node16'
  main: 'index.js'
